### ISSUE TITLE
8.9.58版本现在不恙登录了

### ISSUE THREAD

**Issue by Fitzgerald-Porthmouth-Koenigsegg** [Hakuin123/MQGA#10]
RT
![QQ截图20241028201943](https://github.com/user-attachments/assets/0f74385e-4315-455c-a1d7-088c46582fd8)
我非常用不惯NTQQ，但这么一搞我必须得用NTQQ了，不知道是否有解决方法

**Comment by Hakuin123** [comment]
每个账号所能登录的最低QQ版本是不一样的，这个属于腾讯的大手.jpg 爱莫能助🥲

![腾讯的大手](https://github.com/user-attachments/assets/5db03b03-b8f9-4290-b74d-87e7bdd82502)
